[2024-11-07T07:36:22.451-1100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T07:36:22.500-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T07:36:22.517-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T07:36:22.518-1100] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-07T07:36:22.548-1100] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract_transform_clean_data> on 2024-11-06 00:00:00+00:00
[2024-11-07T07:36:22.564-1100] {standard_task_runner.py:72} INFO - Started process 223867 to run task
[2024-11-07T07:36:22.569-1100] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_cleaned_data_to_mongodb', 'wait_for_extract_transform_clean_data', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/load_cleaned_data_to_mongodb.py', '--cfg-path', '/tmp/tmplt7iyhpk']
[2024-11-07T07:36:22.571-1100] {standard_task_runner.py:105} INFO - Job 32: Subtask wait_for_extract_transform_clean_data
[2024-11-07T07:36:22.616-1100] {standard_task_runner.py:124} ERROR - Failed to execute job 32 for task wait_for_extract_transform_clean_data (invalid interpolation syntax in '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s' at position 5; 223867)
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 447, in task_run
    conf.read_dict(conf_dict, source=args.cfg_path)
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/configuration.py", line 1317, in read_dict
    super().read_dict(dictionary=dictionary, source=source)
  File "/usr/lib/python3.11/configparser.py", line 770, in read_dict
    self.set(section, key, value)
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/configuration.py", line 1346, in set
    super().set(section, option, value)
  File "/usr/lib/python3.11/configparser.py", line 1220, in set
    super().set(section, option, value)
  File "/usr/lib/python3.11/configparser.py", line 910, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s' at position 5
[2024-11-07T07:36:22.662-1100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-07T07:36:22.729-1100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-07T07:36:22.732-1100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-07T09:18:03.905-1100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T09:18:03.915-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T09:18:03.921-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T09:18:03.922-1100] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-07T09:18:03.934-1100] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract_transform_clean_data> on 2024-11-06 00:00:00+00:00
[2024-11-07T09:18:03.943-1100] {standard_task_runner.py:72} INFO - Started process 326491 to run task
[2024-11-07T09:18:03.948-1100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_cleaned_data_to_mongodb', 'wait_for_extract_transform_clean_data', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/load_cleaned_data_to_mongodb.py', '--cfg-path', '/tmp/tmp3prgmeij']
[2024-11-07T09:18:03.949-1100] {standard_task_runner.py:105} INFO - Job 31: Subtask wait_for_extract_transform_clean_data
[2024-11-07T09:18:03.989-1100] {task_command.py:467} INFO - Running <TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [running]> on host debian
[2024-11-07T09:18:04.042-1100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_cleaned_data_to_mongodb' AIRFLOW_CTX_TASK_ID='wait_for_extract_transform_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-06T00:00:00+00:00'
[2024-11-07T09:18:04.043-1100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-07T09:18:04.043-1100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-07T09:18:04.044-1100] {logging_mixin.py:190} INFO - Current task name:wait_for_extract_transform_clean_data state:running start_date:2024-11-07 20:18:03.916277+00:00
[2024-11-07T09:18:04.044-1100] {logging_mixin.py:190} INFO - Dag name:load_cleaned_data_to_mongodb and current dag run status:running
[2024-11-07T09:18:04.044-1100] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-07T09:18:04.044-1100] {baseoperator.py:416} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-11-07T09:18:04.044-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:18:04.046-1100] {logging_mixin.py:190} WARNING - /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/session.py:97 DeprecationWarning: This method is deprecated and will be removed in future.
[2024-11-07T09:19:04.050-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:20:04.056-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:20:55.455-1100] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-11-07T09:20:55.456-1100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-07T09:20:55.493-1100] {process_utils.py:132} INFO - Sending 15 to group 326491. PIDs of all processes in the group: [326491]
[2024-11-07T09:20:55.494-1100] {process_utils.py:87} INFO - Sending the signal 15 to group 326491
[2024-11-07T09:20:55.495-1100] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-07T09:20:55.505-1100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/sensors/base.py", line 334, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-07T09:20:55.513-1100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-07T09:20:55.513-1100] {logging_mixin.py:190} INFO - Task start:2024-11-07 20:18:03.916277+00:00 end:2024-11-07 20:20:55.512272+00:00 duration:171.595995
[2024-11-07T09:20:55.514-1100] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_for_extract_transform_clean_data> dag:<DAG: load_cleaned_data_to_mongodb> dagrun:<DagRun load_cleaned_data_to_mongodb @ 2024-11-06 00:00:00+00:00: scheduled__2024-11-06T00:00:00+00:00, state:running, queued_at: 2024-11-07 20:07:38.168671+00:00. externally triggered: False>
[2024-11-07T09:20:55.514-1100] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-07T09:20:55.515-1100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=load_cleaned_data_to_mongodb, task_id=wait_for_extract_transform_clean_data, run_id=scheduled__2024-11-06T00:00:00+00:00, execution_date=20241106T000000, start_date=20241107T201803, end_date=20241107T202055
[2024-11-07T09:20:55.534-1100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-07T09:20:55.587-1100] {process_utils.py:80} INFO - Process psutil.Process(pid=326491, status='terminated', exitcode=2, started='21:18:03') (326491) terminated with exit code 2
