[2024-11-07T07:35:14.459-1100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T07:35:14.508-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T07:35:14.522-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T07:35:14.523-1100] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-07T07:35:14.548-1100] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract_transform_clean_data> on 2024-11-06 00:00:00+00:00
[2024-11-07T07:35:14.563-1100] {standard_task_runner.py:72} INFO - Started process 221076 to run task
[2024-11-07T07:35:14.570-1100] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_cleaned_data_to_mongodb', 'wait_for_extract_transform_clean_data', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/load_cleaned_data_to_mongodb.py', '--cfg-path', '/tmp/tmpcmqf1ufc']
[2024-11-07T07:35:14.572-1100] {standard_task_runner.py:105} INFO - Job 30: Subtask wait_for_extract_transform_clean_data
[2024-11-07T07:35:14.614-1100] {standard_task_runner.py:124} ERROR - Failed to execute job 30 for task wait_for_extract_transform_clean_data (invalid interpolation syntax in '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s' at position 5; 221076)
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 447, in task_run
    conf.read_dict(conf_dict, source=args.cfg_path)
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/configuration.py", line 1317, in read_dict
    super().read_dict(dictionary=dictionary, source=source)
  File "/usr/lib/python3.11/configparser.py", line 770, in read_dict
    self.set(section, key, value)
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/configuration.py", line 1346, in set
    super().set(section, option, value)
  File "/usr/lib/python3.11/configparser.py", line 1220, in set
    super().set(section, option, value)
  File "/usr/lib/python3.11/configparser.py", line 910, in set
    value = self._interpolation.before_set(self, section, option,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 403, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in '[%(asctime)s] {%(filename)s:%(lineno)d} %(levelname)s - %(message)s' at position 5
[2024-11-07T07:35:14.663-1100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-07T07:35:14.720-1100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-07T07:35:14.723-1100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-07T09:07:41.046-1100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T09:07:41.058-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T09:07:41.065-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T09:07:41.066-1100] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-07T09:07:41.080-1100] {taskinstance.py:2889} INFO - Executing <Task(ExternalTaskSensor): wait_for_extract_transform_clean_data> on 2024-11-06 00:00:00+00:00
[2024-11-07T09:07:41.091-1100] {standard_task_runner.py:72} INFO - Started process 322658 to run task
[2024-11-07T09:07:41.096-1100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'load_cleaned_data_to_mongodb', 'wait_for_extract_transform_clean_data', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/load_cleaned_data_to_mongodb.py', '--cfg-path', '/tmp/tmpigfdg9px']
[2024-11-07T09:07:41.097-1100] {standard_task_runner.py:105} INFO - Job 22: Subtask wait_for_extract_transform_clean_data
[2024-11-07T09:07:41.141-1100] {task_command.py:467} INFO - Running <TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [running]> on host debian
[2024-11-07T09:07:41.207-1100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_cleaned_data_to_mongodb' AIRFLOW_CTX_TASK_ID='wait_for_extract_transform_clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-06T00:00:00+00:00'
[2024-11-07T09:07:41.209-1100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-07T09:07:41.209-1100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-07T09:07:41.209-1100] {logging_mixin.py:190} INFO - Current task name:wait_for_extract_transform_clean_data state:running start_date:2024-11-07 20:07:41.058795+00:00
[2024-11-07T09:07:41.210-1100] {logging_mixin.py:190} INFO - Dag name:load_cleaned_data_to_mongodb and current dag run status:running
[2024-11-07T09:07:41.210-1100] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-07T09:07:41.210-1100] {baseoperator.py:416} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-11-07T09:07:41.210-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:07:41.212-1100] {logging_mixin.py:190} WARNING - /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/session.py:97 DeprecationWarning: This method is deprecated and will be removed in future.
[2024-11-07T09:08:41.217-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:09:41.222-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:10:41.229-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:11:41.237-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:12:41.245-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:13:41.253-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:14:41.262-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:15:41.269-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:16:41.272-1100] {external_task.py:258} INFO - Poking for tasks ['remove_duplicates'] in dag extract_transform_clean_data on 2024-11-06T00:00:00+00:00 ... 
[2024-11-07T09:16:59.719-1100] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-07T09:16:59.761-1100] {process_utils.py:132} INFO - Sending 15 to group 322658. PIDs of all processes in the group: [322658]
[2024-11-07T09:16:59.762-1100] {process_utils.py:87} INFO - Sending the signal 15 to group 322658
[2024-11-07T09:16:59.762-1100] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-07T09:16:59.769-1100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/sensors/base.py", line 334, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, poke_count))
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-11-07T09:16:59.775-1100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-07T09:16:59.776-1100] {logging_mixin.py:190} INFO - Task start:2024-11-07 20:07:41.058795+00:00 end:2024-11-07 20:16:59.775081+00:00 duration:558.716286
[2024-11-07T09:16:59.776-1100] {logging_mixin.py:190} INFO - Task:<Task(ExternalTaskSensor): wait_for_extract_transform_clean_data> dag:<DAG: load_cleaned_data_to_mongodb> dagrun:<DagRun load_cleaned_data_to_mongodb @ 2024-11-06 00:00:00+00:00: scheduled__2024-11-06T00:00:00+00:00, state:running, queued_at: 2024-11-07 20:07:38.168671+00:00. externally triggered: False>
[2024-11-07T09:16:59.776-1100] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2024-11-07T09:16:59.776-1100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=load_cleaned_data_to_mongodb, task_id=wait_for_extract_transform_clean_data, run_id=scheduled__2024-11-06T00:00:00+00:00, execution_date=20241106T000000, start_date=20241107T200741, end_date=20241107T201659
[2024-11-07T09:16:59.793-1100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-07T09:16:59.814-1100] {process_utils.py:80} INFO - Process psutil.Process(pid=322658, status='terminated', exitcode=2, started='21:07:40') (322658) terminated with exit code 2
[2024-11-07T09:17:03.782-1100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T09:17:03.789-1100] {taskinstance.py:2603} INFO - Dependencies not met for <TaskInstance: load_cleaned_data_to_mongodb.wait_for_extract_transform_clean_data scheduled__2024-11-06T00:00:00+00:00 [up_for_retry]>, dependency 'Not In Retry Period' FAILED: Task is not ready for retry yet but will be retried automatically. Current date is 2024-11-07T20:17:03.789159+00:00 and task will be retried at 2024-11-07T20:17:59.775081+00:00.
[2024-11-07T09:17:03.793-1100] {local_task_job_runner.py:166} INFO - Task is not able to be run
